[project]
name = "proctools"
version = "0.2.1"
authors = [
    { name="Ariel Ladegaard", email="arl13@aber.ac.uk" },
    { name="Alun Jones", email="alj118@aber.ac.uk" }
]
description = "ProcTools - Common tools for (ExoMars) data product processing software"
readme = "README.md"
license = "MIT"
keywords = ["processing", "PDS4", "ExoMars"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Physics",
  "Topic :: Scientific/Engineering",
  "Topic :: Utilities",
]
requires-python = ">=3.13"
dependencies = [
    "lxml>=6.0.0",
    "numpy>=2.3.2",
    "passthrough",
    "pds4-tools>=1.4",
]

[project.urls]
Repository = "https://github.com/ExoMars-PanCam/acp"

[project.optional-dependencies]
cli = [
    "typer>=0.16.0",
]

[build-system]
requires = [ "uv_build" ]
build-backend = "uv_build"

[tool.uv.sources]
passthrough = { path = "../passthrough" }

